.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. interchained_qt test_interchained_qt
clean: FORCE
	$(MAKE) -C .. interchained_qt_clean test_interchained_qt_clean
check: FORCE
	$(MAKE) -C .. test_interchained_qt_check
interchained-qt interchained-qt.exe: FORCE
	 $(MAKE) -C .. interchained_qt
